### ISSUE TITLE
Add header/footer out of items

### ISSUE THREAD

**Issue by abuenofacephi** [realityexpander/DragDropColumnCompose#1]
https://github.com/realityexpander/DragDropColumnCompose/blob/b37b1922b4575b230590917c01e90b7405e59eee/app/src/main/java/com/example/dragdropcolumncompose/MainActivity.kt#L42

Hello!

I'm looking for add a header like that in LazyColumn:

``` 
LazyColumn(
        verticalArrangement = Arrangement.spacedBy(8.dp),
        modifier = modifier
            .padding(8.dp)
            .fillMaxSize()
    ) {
       //Header
        item {
            Text(text = "Active las acciones que quiera realizar:")
            Spacer(Modifier.height(8.dp))
        }
        items(components) { component ->
```

Maybe I pass toDragDropColumn another content, but its weird.

Good job!
Best regards

**Comment by realityexpander** [comment]
Hey! Sorry for the late reply, I just saw this message today!

This may be easier to do now.

Have you tried it lately?
